version: "3.3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${DEFAULT_PASSWORD}
      - MYSQL_DATABASE=ecot13
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "10001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${DEFAULT_PASSWORD}
      - PMA_ARBITRARY=1

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./neo4j/conf:/conf"
      - "./neo4j/data:/data"
      - "./neo4j/import:/import"
      - "./neo4j/logs:/logs"
      - "./neo4j/plugins:/plugins"

  oracle:
    build: ./oracle
    ports:
      - "5500:5500"
      - "1521:1521"
    volumes:
      - "./oracle/oradata:/opt/oracle/oradata"
    environment:
      - ORACLE_PWD=${DEFAULT_PASSWORD}

volumes:
  mysql-data:
